baseurl = "http://rachel-robot.com/"
languageCode = "en-us"
title = "Rachel Robot"
theme = "moogone"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About Me"
    url = "/page/about/"
    weight = 2

[[menu.main]]
    name = "Teaching Philosophy"
    url = "/page/teaching-philosophy/"
    weight = 3

[[menu.main]]
    name = "Documents"
    url = "/page/documents/"
    weight = 4
